service: covid-19

plugins:
  - serverless-domain-manager
  - serverless-plugin-warmup

custom:
  customDomain:
    domainName: api.covid-19.derkachhub.com
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
  settings:
    ACCOUNT_ID: "338027781746"
    REGION: "eu-central-1"
    DATABASE_NAME: "covid-19"
    ACTUAL_DATA_PARSER_QUEUE_URL: "https://sqs.eu-central-1.amazonaws.com/338027781746/covid-19-actual-data-parser"
    ARCHIVE_DATA_PARSER_QUEUE_URL: "https://sqs.eu-central-1.amazonaws.com/338027781746/covid-19-archive-data-parser"
    ARCHIVE_SESSION_CREATOR_QUEUE_URL: "https://sqs.eu-central-1.amazonaws.com/338027781746/covid-19-archive-session-creator"
    ARCHIVE_DELTAS_CALCULATOR_QUEUE_URL: "https://sqs.eu-central-1.amazonaws.com/338027781746/covid-19-archive-deltas-calculator"
    ARCHIVE_DELTAS_SESSION_MARKER_QUEUE_URL: "https://sqs.eu-central-1.amazonaws.com/338027781746/covid-19-archive-deltas-session-marker"

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512
  region: eu-central-1
  stage: prod
  environment: ${self:custom.settings}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:sendMessage"
      Resource: "arn:aws:sqs:${self:provider.region}:${self:provider.environment.ACCOUNT_ID}:covid-19*"
    - Effect: "Allow"
      Action:
        - "ssm:Describe*"
        - "ssm:Get*"
        - "ssm:List*"
      Resource: "*"
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
        - Fn::Join:
          - ':'
          - - arn:aws:lambda
            - Ref: AWS::Region
            - Ref: AWS::AccountId
            - function:${self:service}-${opt:stage, self:provider.stage}-*

functions:
  actualScheduler:
      handler: handlers/actualScheduler.handler
      timeout: 30
      events:
        - schedule: rate(1 minute)

  archiveScheduler:
    handler: handlers/archiveScheduler.handler
    timeout: 30
    events:
      - schedule: rate(1 minute)

  archiveDeltasScheduler:
    handler: handlers/archiveDeltasScheduler.handler
    timeout: 30
    events:
      - schedule: rate(1 minute)

  actualDataParser:
      handler: handlers/actualDataParser.handler
      timeout: 30
      events:
        - sqs:
            arn: "arn:aws:sqs:${self:provider.region}:${self:provider.environment.ACCOUNT_ID}:covid-19-actual-data-parser"
            batchSize: 1
            enabled: true

  archiveSessionCreator:
    handler: handlers/archiveSessionCreator.handler
    timeout: 30
    events:
      - sqs:
          arn: "arn:aws:sqs:${self:provider.region}:${self:provider.environment.ACCOUNT_ID}:covid-19-archive-session-creator"
          batchSize: 1
          enabled: true

  archiveDataParser:
    handler: handlers/archiveDataParser.handler
    timeout: 30
    events:
      - sqs:
          arn: "arn:aws:sqs:${self:provider.region}:${self:provider.environment.ACCOUNT_ID}:covid-19-archive-data-parser"
          batchSize: 1
          enabled: true

  archiveDeltasCalculator:
    handler: handlers/archiveDeltasCalculator.handler
    timeout: 900
    reservedConcurrency: 5
    memorySize: 1024
    events:
      - sqs:
          arn: "arn:aws:sqs:${self:provider.region}:${self:provider.environment.ACCOUNT_ID}:covid-19-archive-deltas-calculator"
          batchSize: 1
          enabled: true

  archiveDeltasSessionMarker:
    handler: handlers/archiveDeltasSessionMarker.handler
    timeout: 900
    reservedConcurrency: 1
    events:
      - sqs:
          arn: "arn:aws:sqs:${self:provider.region}:${self:provider.environment.ACCOUNT_ID}:covid-19-archive-deltas-session-marker"
          batchSize: 1
          enabled: true

  getActualSummary:
    handler: handlers/getActualSummary.handler
    warmup: true
    events:
      - http:
          path: actual/summary
          method: get